name: Project Board Automation (External Script Version)

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, closed]
  schedule:
    # Run every hour
    - cron: '0 */1 * * *'
  workflow_dispatch:

concurrency:
  group: 'project-automation-external'
  cancel-in-progress: true

jobs:
  update-project-dates:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
      repository-projects: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: print directories under .github
        run: |
          echo "Directories under .github:"
          ls -l .github
          echo "Directories under .github/scripts:"
          ls -l .github/scripts
      - name: Update project item dates
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_PAT }}
          script: |
            const script = require('.github/scripts/update-project-item-dates.js');
            await script({github, context, core})
