name: SVG Creator
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write # for creating a pull request

jobs:
  create-update-svg:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find all XML files in .diagrams folder
        id: find-xml
        run: |
          echo "xml_files=$(find .diagrams -name "*.xml" -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - name: Set up cache for apt
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-drawio-${{ hashFiles('**/svg-creator.yaml') }}
          restore-keys: |
            ${{ runner.os }}-apt-drawio

      - name: install drawio binary
        run: |
          sudo apt-get update
          sudo apt-get install -y drawio
      - name: Create SVG files
        if: steps.find-xml.outputs.xml_files != ''
        run: |
          IFS=' ' read -r -a xml_files <<< "${{ steps.find-xml.outputs.xml_files }}"
          for file in "${xml_files[@]}"; do
            svg_file="${file%.xml}.svg"
            drawio --export --format svg --output "$svg_file" "$file"
          done
      - name: Commit files to PR branch
        if: steps.find-xml.outputs.xml_files != ''
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add .diagrams/*.svg 
          git commit -m "Add SVG files from XML diagrams" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
        
